/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6752. Copyright MediaTek Inc. (C) 2013.
 * Thu Jun 18 10:22:09 2015
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_BPI1     GPIO_VIO18
#define GPIO_DVDD28_BPI2     GPIO_VIO18
#define GPIO_DVDD28_MD     GPIO_VIO18
#define MSDC_POWER_MC1     MSDC_VMC


